### ISSUE TITLE
Создать базовую структуру

### ISSUE THREAD

**Issue by alexbogovich** [ADDinc/style_music#1]
Базовый makefile, gitignore
Генерация папок

**Comment by Chillten** [comment]
В зависимости от метода подключение и сборки модуля essentia, роль makefile-а будет специфичной

**Comment by alexbogovich** [comment]
Пример компиляции с использованием essentia
http://essentia.upf.edu/documentation/FAQ.html#how-to-compile-my-own-c-code-that-uses-essentia
Желательно уточнить у преподавателя по поводу установки доп пакетов, тк они могут понадобиться
