### ISSUE TITLE
Подключение модуля Essentia

### ISSUE THREAD

**Issue by alexbogovich** [ADDinc/style_music#2]
Разобраться как лучше подключить модуль essentia в проект, так же следует оптимизировать его сбору. Что касается ключей для конфигурации, думаю хватит ./waf configure --mode=release --build-static

**Comment by alexbogovich** [comment]
Модуль будет отдельно собираться в thirdparty и оттуда будут подключаться заголовочные файлы. Необходимо чтобы сборка была всего один раз.

**Comment by alexbogovich** [comment]
Проблема с компиляцией файла использующий библиотеку essentia:
```
g++ -pipe -Wall -O2 -fPIC -I /usr/local/include/essentia/ -I /usr/local/include/essentia/scheduler/ -I /usr/local/include/essentia/streaming/  -I /usr/local/include/essentia/utils -I /usr/include/taglib -I /usr/local/include/gaia2 -I /usr/include/qt4 -I /usr/include/qt4/QtCore -D__STDC_CONSTANT_MACROS src/main.cpp -o standard_mfcc -L /usr/local/lib -lessentia -lfftw3 -lyaml -lavcodec -lavformat -lavutil -lsamplerate -ltag -lfftw3f

usr/bin/ld: /usr/local/lib/libessentia.a(audioloader.cpp.1.o): undefined reference to symbol 'avresample_alloc_context@@LIBAVRESAMPLE_3'
//usr/local/lib/libavresample.so.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
Временное решение это компиляция средствами waf, но необходимо что бы была статическая библиотека
При конфигурации waf можно указать место создание библиотеки, с помощью ключа --prefix="Путь"

**Comment by alexbogovich** [comment]
Проблема решается отчисткой usr/local/lib и usr/local/include, в случаи если это не возможно, то необходимо удалить  libav* файлы в след папках:
/usr/local/include/
/usr/local/lib/
/usr/local/lib/pkgconfig/
Так же необходимо удалить все связанное с essentia.
Для полной уверенности можно переустановить все связанные с этим пакеты, те
sudo apt-get purge build-essential libyaml-dev libfftw3-dev libavcodec-dev libavformat-dev libavutil-dev libavresample-dev python-dev libsamplerate0-dev libtag1-dev

И затем
```
sudo apt-get install build-essential libyaml-dev libfftw3-dev libavcodec-dev libavformat-dev libavutil-dev libavresample-dev python-dev libsamplerate0-dev libtag1-dev

sudo apt-get install python-numpy-dev python-numpy python-yaml

./waf configure --mode=release --build-static --with-python --with-cpptests --with-examples --with-vamp

./waf

sudo ./waf install
```

После проделанный команд в успеха сборки, библиоткека essentia будет установлена по умочанию в /usr/local/
Следующим этапом можно проверить видимость библиотеки essentia с помощью тестов ./waf run_tests, в случаи если появляется ошибка 
`ImportError: libessentia.so: cannot open shared object file: No such file or directory`
Необходимо добавить /usr/local/lib в LD_LIBRARY_PATH
[Указания](http://stackoverflow.com/questions/13428910/how-to-set-the-environmental-variable-ld-library-path-in-linux)
После должны работать тесты и собираться исходики спользующие заголовки данной библиотеки

**Comment by alexbogovich** [comment]
Но в идеале библиотека должна собиралась локально в конкретной папке и количество зависимостей, необходимо ограничить используемыми алгоритами.

**Comment by d-dyachkov** [comment]
Полный билд динамической, кину пока сюда, чтобы не потерять
sudo apt-get purge build-essential libyaml-dev libfftw3-dev libavcodec-dev libavformat-dev libavutil-dev libavresample-dev python-dev libsamplerate0-dev libtag1-dev
sudo apt autoremove
sudo rm -fR /usr/local/include/essentia/
sudo rm -fR /usr/local/lib/\*essentia\*
sudo rm -fR /usr/local/lib/vamp/
sudo rm -fR /usr/local/lib/pkgconfig/
sudo rm -fR /usr/local/lib/pythonX.X/dist-packages/essentia/
rm -fR build/*
sudo apt-get install build-essential libyaml-dev libfftw3-dev libavcodec-dev libavformat-dev libavutil-dev libavresample-dev python-dev libsamplerate0-dev libtag1-dev
sudo apt-get install python-numpy-dev python-numpy python-yaml
sudo apt autoremove
./waf configure --mode=release --with-vamp
./waf
sudo ./waf install
LD_LIBRARY_PATH=/usr/local/lib:$(LD_LIBRARY_PATH)
export LD_LIBRARY_PATH

**Comment by d-dyachkov** [comment]
Сборка статической
./waf configure --mode=release --build-static --prefix=../..
g++ -I include src/main.cpp -o main -Llib -lessentia -lfftw3 -lyaml -lavcodec -lavformat -lavutil -lavresample -lsamplerate -ltag -lfftw3f
